version: "3.9"
services:
  redis:
    image: "redis:latest"
    ports:
      - "16379:6379"
    restart: always
    networks:
      - ratelimiter
  zookeeper:
    image: "zookeeper:latest"
    ports:
      - "12181:2181"
    restart: always
    networks:
      - ratelimiter
networks:
  ratelimiter:
    name: ratelimiter