[log]
env = "local"
app_id = "rate_limiter"
debug = true
level = 0

[http]
mode = "debug"
port = ":18080"
dump = false

[redis]
addr = "127.0.0.1:16379"

[rateLimit]
max_count = 60
rate_limit_sec = 60

[zookeeper]
addr = "127.0.0.1:12181"